# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

'''
Name     : Rupesh Garsondiya
github   : @Rupeshgarsondiya
Topic    : Gradient descent in Neural Network Deep-learning(DL)
Refrance : Campus X Deep-Learning
'''

# import required library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.datasets import make_circles

# load the data
X, y = make_circles(n_samples=100, random_state=42)

# plot the data
plt.scatter(X[:, 0], X[:, 1], c=y)
plt.show()

print(X.shape)
print(y.shape)

"""# Gradient descent
 - It is an optimazation algoritham
 - In this algoritham we calculate the gradient
 - calculate partial derivate of loss function with respect to    weight and bais

# Types of Gradient descent
 - Batch Gradient descent
 - Mini Batch Gradient descent
 - Sochastic Gradient descent

#Batch Gradient Descent

**Pseudo code:**

     for i in range(epochs):
         1. Calculate predictions for the entire dataset.  
         2. Calculate the loss.  
         3. Update weights and biases.  

- In batch gradient descent, the total number of weight updates is equal to the number of epochs.
- This is also referred to as Vanilla Gradient Descent.
- It is faster compared to the other two gradient descent algorithms.
- In this approach, we use the entire dataset at once for each update.
- Batch Gradient Descent (BGD) does not work well with functions that have both local and global minima. If BGD reaches a local minimum, it may never escape to find the global minimum. This problem is overcome by Stochastic Gradient Descent (SGD).
"""

# Example
# Design neural network model(Architecture same for all GD)
model = Sequential()
model.add(Dense(2, activation='sigmoid', input_shape=(2,)))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()
start = time.time()
GD_history = model.fit(X, y, epochs=100,batch_size=X.shape[0],validation_split= 0.2)
# Batch size hyper parameter is for diffrent type gradient descent algotitham
# if batch size = no of row , it work as batch gradient descent
t_time = time.time()-start
print('Total training time : ',t_time)

"""# Batch Gradient Descent

**Pesudo code : **

       for i in epochs:

           for j in X.shape[0]:

                 1. Shuffle the data.
                 2. Select a row randomly.
                 3. Calculate the output for the selected row.
                 4. Calculate the loss.
                 5. Update the weights and biases .
      
  - SGD converges faster than the other two gradient descent algorithms.
  - The loss graph of SGD is spiky, and this characteristic helps in situations where both local and global minima are present.
  - SGD is slower in terms of training time.
"""

# Example stochastic gradient descent
model1 = Sequential()
model1.add(Dense(2, activation='sigmoid', input_shape=(2,)))
model1.add(Dense(1, activation='sigmoid'))
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model1.summary()
start1 = time.time()
SGD_history = model1.fit(X, y, epochs=100,batch_size=1,validation_split=0.2)
t_time1 = time.time()-start1
print('Total training time : ',t_time1) # This funtion time give in second

"""# Loss graph GD vs SGD"""

plt.plot(GD_history.history['loss'], label='GD')
plt.plot(SGD_history.history['loss'], label='SGD')
plt.legend( ['GD loss','SGD loss'])
plt.show()

plt.plot(GD_history.history['accuracy'], label='GD')
plt.plot(SGD_history.history['accuracy'], label='SGD')
plt.legend()
plt.show()

# here we clearly so spiky nature in loss and  accuracy both graph

"""# Mini Batch Gradient Descent

**Pesudo code : **
        
         for i in range(epochs):
              
              for i in range(no of batch):
                   
                   1. calculate prediction for batch(vectorization)
                   2. calculate loss
                   3. update weight and baises


- We need to specify the batch size.
- The total number of batches = n/batch_sizen/batch_size (where nn is the total number of rows in the dataset).
- This algorithm is a mix of Gradient Descent (GD) and Stochastic Gradient Descent (SGD).
- The batch size is typically a power of 2, as it is an efficient way to utilize memory (RAM). (This was asked in an interview with a CampusX student.)
- It has a less spiky nature compared to SGD.
"""

# example of mini batch gradient descent

model2 = Sequential()
model2.add(Dense(2, activation='sigmoid', input_shape=(2,)))
model2.add(Dense(1, activation='sigmoid'))
model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model2.summary()
start2 = time.time()
MBGD_history = model2.fit(X, y, epochs=10,batch_size=10,validation_split=0.2)
t_time2 = time.time()-start2
print('Total training time : ',t_time2)

"""# Loss graph Mini Batch GD and Stochastic GD"""

plt.plot(MBGD_history.history['loss'], label='MBGD')
plt.plot(SGD_history.history['loss'], label='SGD')
plt.legend( ['MBGD loss','SGD loss'])
plt.show()

plt.plot(MBGD_history.history['accuracy'], label='MBGD')
plt.plot(SGD_history.history['accuracy'], label='SGD')
plt.legend()
plt.show()

